idf_component_register(SRCS "app_main.cpp" "wifi.cpp" "api.cpp" "mqtt.cpp" "jiecang_rj12.cpp" "jiecang_jarvis_rj45.cpp" "jiecang_transport.cpp" "jiecang_jcb35n2.cpp" "loctek_transport.cpp" INCLUDE_DIRS "../include" REQUIRES app_update cjson driver esp_event esp_http_server esp_netif esp_wifi littlefs mdns mqtt nvs_flash)
